### ISSUE TITLE
How can I get started confluent

### ISSUE THREAD

**Issue by bybai** [xcat2/confluent#104]
Hi @jjohnson42,

I have great interests in confluent, but I cannot find doc about it.
So how can I get started about confluent?

**Comment by jjohnson42** [comment]
Currently, the most of the user doc is in hpc.lenovo.com currently.

There's a demonstration video at https://www.youtube.com/watch?v=1kMrY4QqzVI
(Though that could probably use a refreshed version)

There is an email link at the bottom to email for more interactive information.

**Comment by bybai** [comment]
Thanks @jjohnson42
