### ISSUE TITLE
What the difference between xnba elilo-x64.efi and bootx64.efi

### ISSUE THREAD

**Issue by bybai** [xcat2/confluent#105]
Hi @jjohnson42 

     When I use netboot=xnba, in some OS and x86_64 servers, it failed to correctly load kernel and initrd, so I have question here,  what the difference between xnba elilo-x64.efi and bootx64.efi?   I think xnba is a good bootloader, and If I want to use xnba and bootx64.efi, do you have some suggestions?

**Comment by jjohnson42** [comment]
You may want to check out a branch:
https://github.com/jjohnson42/xcat-core/tree/noelilo

The lenovobuild2.14 branch has removed elilo usage where possible.  For this issue, I went through and I cherry-picked what I think are the relevant commits for your review.

For kernels RHEL7 and newer and similar vintage of other distributions, it just boots the kernel directly from iPXE without an additional loader.

**Comment by bybai** [comment]
@jjohnson42, thanks your branch here.

Could you have example or doc to use this branch to  just boots the kernel directly from iPXE without an additional loader?   Do I just set "netboot=xnba" and "nodeset ....."?

When I want to provision OS on lenovo x86_64 servers, I used "xnba" very well for CentOS, but for other specific customized OS based on CentOS, I need to use "bootx64.efi". 
For example:
In dhcpd.conf, when the "client-architecture = 00:07", filename is xnba.efi, but some times, I need to change  it to "bootx64.efi",  now I just update dhcpd.conf manually. So when client-architecture is the same, and in different cases, it need different bootloader, do you have suggestions that can handle use different boot loader automatically?  

In dhcp.pm line 692:
```
else if option client-architecture = 00:07 { filename = \"xcat/xnba.efi\"; }
```

**Comment by jjohnson42** [comment]
So if it is that branch, then it works as normal, it changes xnba.pm.

If you want to try them as a yum repo, then the lenovobuild does it:
https://hpc.lenovo.com/users/downloads/

Follow the normal xnba procedure and it will skip elilo in the branch.

Note that bootx64.efi is a generic name, so more details may be required if the direct boot kernel/initrd does not work.

**Comment by bybai** [comment]
Hi @jjohnson42 , I downloaded xcat-core-noelilo.zip, and had a try to install the MN. I noticed /etc/dhcp/dhcpd.conf is the same with generated by xcat-core. I set "chdef kvm1 netboot=xnba", how I confirm if it is use elilo or not?  there are "kvm1, kvm1.elilo, kvm1.uefi" under /tftpboot/xcat/xnba/nodes. So I confused.

**Comment by jjohnson42** [comment]
The .elilo file is only used if the .uefi file says to try to use it.

If the .uefi file has a kernel and initrd in it, it is skipping elilo.

**Comment by jjohnson42** [comment]
ok, I believe this is all addressed with recent changes to skip elilo.
