### ISSUE TITLE
it takes a long time to get the  state of nodes  if I add a server about HPE

### ISSUE THREAD

**Issue by wujianqiangwjq** [xcat2/confluent#106]
gpu01 configuration: 
    Manufacturer: HPE
    Product Name: ProLiant XL270d Gen10

confetty
-> ls nodes
c01n01/
c01n02/
gpu01/
io01/
io02/
mgt01/
-> cd /noderange/everything/power
-> cat  state
cat state
c01n01: state="on"
c01n02: state="on"
io01: state="on"
io02: state="on"
mgt01: state="on"
....
here is very slow

**Comment by jjohnson42** [comment]
Does it hang forever or does it eventually error or work?

Does it change if you do:
```
nodeattrib gpu01 hardwaremanagement.method=redfish
```
Does:
```
ipmitool -I lanplus -H <name/ip of gpu01 bmc> -U username -P password chassis status 
```
work?

**Comment by wujianqiangwjq** [comment]
Not forever.  the final result:   gpu01: timeout
 Just it takes a long time to get the result for the gpu01 node. It's based on what I know that  the  configuration is  "hardwaremanagement.method = ipmi" about gpu01. I had a try to execute the command "ipmitool -I lanplus -H <name/ip of gpu01 bmc> -U username -P password sdr "  But it didn't work

**Comment by jjohnson42** [comment]
Can you try to set it to redfish and see what happens?

It would seem the ilo in question probably has ipmi disabled.  It may have redfish enabled.
________________________________

**Comment by wujianqiangwjq** [comment]
the reslut is that  gpu01: redfish is not a supported plugin. the ipmi is disable about gpu01.
![1](https://user-images.githubusercontent.com/20573480/77131557-f1a54400-6a96-11ea-8f36-6f59e5edb6d7.JPG)
![2](https://user-images.githubusercontent.com/20573480/77131571-ff5ac980-6a96-11ea-806f-cc119c504095.JPG)

**Comment by jjohnson42** [comment]
Are you able to update to a newer confluent and pyghmi?  confetty show version


________________________________

**Comment by jjohnson42** [comment]
the server in question has ipmi disabled, either ipmi would have to be enabled or a newer version of pyghmi/confluent is required to use redfish.
