### ISSUE TITLE
it takes a  long time to get the data about energy and temperature

### ISSUE THREAD

**Issue by wujianqiangwjq** [xcat2/confluent#108]
the cluster:  821 compute nodes
cat /noderange/everything/sensors/hardware/energy/all
02c02n04: sensors=[
 {
  "name": "DC Energy", 
  "state_ids": [], 
  "value": 30.58287145277778, 
  "states": [], 
  "health": "ok", 
  "units": "kWh", 
  "type": "Energy"
 }
]
r14c01n11: sensors=[
 {
  "name": "DC Energy", 
  "state_ids": [], 
  "value": 55.889863706944446, 
  "states": [], 
  "health": "ok", 
  "units": "kWh", 
  "type": "Energy"
 }
]
...

here will be blocking  a long long time

**Comment by jjohnson42** [comment]
This one I believe was diagnosed to waiting on nodes to timeout that were non responsive.
