### ISSUE TITLE
Add TLS Configuration Options

### ISSUE THREAD

**Issue by nealep** [xcat2/confluent#110]
We recently discovered that our XCat 2.15 deployment using goconserver was susceptible to the SWEET32 attack due to hard coded TLS Cipher suites. While it doesn't look like confluent allows DES based ciphers, it made sense to me to request that confluent support configurable TLS options in order to quickly mitigate vulnerabilities discovered in the future.

Specifically, I think it will be prudent to allow runtime configuration of the allowed TLS versions and the allowed cipher suites. 

More information on the mentioned patch can be found [here](https://github.com/xcat2/goconserver/pull/64) and information on the vulnerabilities can be found at https://www.openssl.org/blog/blog/2016/08/24/sweet32/ and https://access.redhat.com/articles/2548661

**Comment by jjohnson42** [comment]
https://github.com/xcat2/confluent/commit/4348d9160bf3c01601d256d62e09b3c2fe001cec

Has been added and will be possible to specify in 3.0.

**Comment by jjohnson42** [comment]
Closing as implemented, feel free to reopen or comment on further
