### ISSUE TITLE
Non-existent endpoint does not return a 404

### ISSUE THREAD

**Issue by canteuni** [xcat2/confluent#113]
Hi again, so I've found another "non existent" endpoint that does not return any error (like in the issue #112 ): 
`/nodes/nodename/configuration/management_controller/users/2/ThisEndpointDoesNotExist`.

I don't know if there are some more enpoints like this, I was wondering if there is a way to generalize the "404 handling" ? For example, having the list of every possible endpoints of the application, and if a request is not contained in this list then return a NotFound error ? But don't know if it's appropriate for your case.

**Comment by jjohnson42** [comment]
I have made a pass at making PluginCollections limit elements to flat by default:
https://github.com/xcat2/confluent/commit/bbe9bc3e066804a6da5f1863c8c11675e587cf39

It will still be up to plugins to ascertain whether a member is missing, but it should generically catch 'path too long' issues like this.

Interested in feedback.
