### ISSUE TITLE
How to implement service node pool for XCAT hierarchical cluster

### ISSUE THREAD

**Issue by ornekofbf** [xcat2/confluent#168]
I am currently working on setting up a hierarchical cluster environment using xCAT and am interested in implementing a service node pool to improve the load balancing and management of our computing resources. Our goal is to ensure that tasks are distributed efficiently among our compute nodes to optimize performance and resource utilization.

In the official document 2.16.5, it was proposed to use a service node pool to achieve load balancing and high availability, but I have not found a specific method or steps to implement a service node pool. I would greatly appreciate it if you could provide guidance on the following aspects:
1.Could you outline the specific steps required to set up a hierarchical cluster service node pool within xCAT?
2.Is there any detailed documentation or tutorials available that cover the setup process from start to finish?

Thank you very much for your time and consideration. I look forward to hearing from you soon.

**Comment by jjohnson42** [comment]
For xCAT or for confluent?

Note that in either case this mostly applies to deployment/diskless boot performance and does not pertain to the compute task workload.

**Comment by ornekofbf** [comment]
Thank you for your reply. I would like to know the implementation steps of xcat's service node pool.

As shown in the document, it seems that xcat has already implemented the corresponding function? But I am still not quite sure about how to create a service node pool and the complete process of binding it with computing nodes. Can you provide guidance?Thank you.













At 2024-10-10 20:51:04, "Jarrod Johnson" ***@***.***> wrote:

For xCAT or for confluent?

Note that in either case this mostly applies to deployment/diskless boot performance and does not pertain to the compute task workload.

**Comment by jjohnson42** [comment]
For xCAT, one document may be:
https://sourceforge.net/p/xcat/wiki/Setting_Up_a_Linux_Hierarchical_Cluster/

You may want to send your query to the xcat-user mailing list https://sourceforge.net/p/xcat/mailman/

Or open issue under xcat2/xcat-core/, where that team is responsible for xCAT service node pools.

**Comment by Obihoernchen** [comment]
Moved to https://github.com/xcat2/xcat-core/issues/7473
