### ISSUE TITLE
Improve customization support of packagelist

### ISSUE THREAD

**Issue by Obihoernchen** [xcat2/confluent#171]
Currently a custom packagelist might fail if udevadm does not detect a driver for install disks.

OS: Alma 9.4, diskful

[getinstalldisk](https://github.com/xcat2/confluent/blob/master/confluent_osdeploy/el8/profiles/default/scripts/getinstalldisk#L38-L54) script is checking DRIVERS via udevadm. If DRIVERS is empty an exception is thrown.

Because of this the [pre.sh](https://github.com/xcat2/confluent/blob/master/confluent_osdeploy/el8/profiles/default/scripts/pre.sh#L115-L127) script does not create a `/tmp/partitioning` file for kickstart.

If NVME multipathing is active (default) the driver detection can fail for NVMEs with multipathing support:
```
# udevadm info -a /dev/nvme0n1 | grep -E 'looking|DRIVERS'
  looking at device '/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1':
  looking at parent device '/devices/virtual/nvme-subsystem/nvme-subsys0':
    DRIVERS==""
```

With nvme multipathing disabled (kcmd: `nvme_core.multipath=N`) it works because a driver is detected:
```
# udevadm info -a /dev/nvme0n1 | grep -E 'looking|DRIVER'
  looking at device '/devices/pci0000:60/0000:60:01.2/0000:61:00.0/nvme/nvme0/nvme0n1':
  looking at parent device '/devices/pci0000:60/0000:60:01.2/0000:61:00.0/nvme/nvme0':
    DRIVERS==""
  looking at parent device '/devices/pci0000:60/0000:60:01.2/0000:61:00.0':
    DRIVERS=="nvme"
  looking at parent device '/devices/pci0000:60/0000:60:01.2':
    DRIVERS=="pcieport"
  looking at parent device '/devices/pci0000:60':
    DRIVERS==""
```

I think this should be fixed. But I also think that it should be ensured that the osimage `partitioning` file is always used if it is customized. Currently a `/tmp/partitioning` file is only created from the osimage `partitioning` file if `getinstalldisk` also finds a driver. This can confuse users (e.g. me :D) if a modified partitioning file is suddenly not used because of this.

**Comment by jjohnson42** [comment]
Need more detail, diskless or diskful and which OS?

**Comment by Obihoernchen** [comment]
Sorry this was just a reminder for me. I added further info above :)

**Comment by jjohnson42** [comment]
Ok, so the package list was a red herring?

Is this change from October relevant?

https://github.com/xcat2/confluent/commit/008c1308b49227a0864751be8e73eaeca21af63e

**Comment by Obihoernchen** [comment]
Yes I just confirmed this fixes the issue.
Didn't have a look at the code sorry.

```
# . /etc/confluent/functions 
# udevadm info -a /dev/nvme0n1 | grep -E 'looking|DRIVER'
  looking at device '/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1':
    DRIVER==""
  looking at parent device '/devices/virtual/nvme-subsystem/nvme-subsys0':
    DRIVERS==""
# ls /tmp/installdisk
ls: cannot access '/tmp/installdisk': No such file or directory
# confluentpython /tmp/getinstalldisk 
Skipping nvme0c0n1: Skipping multipath devname
Skipping nvme0n1: No driver detected
Skipping nvme0n1p1: Not a disk
Skipping nvme1c1n1: Skipping multipath devname
Skipping nvme1n1: No driver detected
Skipping nvme1n1p1: Not a disk
Skipping nvme1n1p2: Not a disk
Skipping nvme1n1p3: Not a disk
# ls /tmp/installdisk
ls: cannot access '/tmp/installdisk': No such file or directory
# confluentpython /tmp/getinstalldisk.master 
Skipping nvme0c0n1: Skipping multipath devname
Skipping nvme0n1p1: Not a disk
Skipping nvme1c1n1: Skipping multipath devname
Skipping nvme1n1p1: Not a disk
Skipping nvme1n1p2: Not a disk
Skipping nvme1n1p3: Not a disk
# ls /tmp/installdisk
/tmp/installdisk
# cat /tmp/installdisk 
nvme0n1
```
