### ISSUE TITLE
console won't open

### ISSUE THREAD

**Issue by psuter80** [xcat2/confluent#62]
consoles.html example is not working due to a cookie issue: when a new console is opened by clicking the button, it won't display anx text, only an empty console and the httpapi.py returns an internal server error 500 and logs the following error: 

httpsessions[authorized['sessionid']]['inflight'].add(mythreadid)
KeyError: 'sessionid'

the reason for this is, that the confluentsessionid cookie that is being sent by the server after the first post request is not included in subsequent post requests when initiating the console session. 

this can be fixed by removing line 293 in httpapi.py: 
  cookie['confluentsessionid']['path'] = '/'
as the XMLHTTPRequest does not use / as path the browser won't send the cookie. removing the mentioned line resolves the issue and consoles are working as expected. 

regards
Pascal

**Comment by jjohnson42** [comment]
I think commit 0ad4ae90c9a4071771bad58c199bfda54086b46d works as requested.

I'll do some quick checks on Monday when I'm back from vacation just in case.

If there's anything interesting you'd like to share about your use case, let me know.

**Comment by jjohnson42** [comment]
Assuming the fix referenced closed the issue.
