### ISSUE TITLE
Possibility of upstream RPMs for latest confluent release

### ISSUE THREAD

**Issue by samveen** [xcat2/confluent#82]
Is it possible that RPMs for the latest release of confluent (`1.5.0`) be added to the confluent repo: http://xcat.org/files/confluent/

**Comment by jjohnson42** [comment]
I can place files there, but I don't have access to the xcat.org signing key, and I presume we'd want the xcat.org key used to sign all packages from xcat.org?

If no one speaks up to care, I'll place the confluent rpms there with the Lenovo signing key for lack of another key to use on my part.

**Comment by whowutwut** [comment]
@jjohnson42  The server is accessed via ssh keys.  There's 3 ssh keys in the authorized_keys file for you.. 

* jjohnson2@x1
* jjohnson2@localhost.localdomain
* jjohnson2@buildabear.labs.lenovo.com


If they are invalid , I can remove them and if you send me another public key via email, I can add it to the xcat user to this server.

**Comment by samveen** [comment]
@jjohnson42  Any luck?

PS. Apologies on being a bother.

**Comment by samveen** [comment]
Marking this as complete as confluent is available as xcat-confluent from the xCAT repositories. For reference:
- http://xcat.org/files/xcat/repos/apt/2.16/xcat-core/pool/main/x/xcat-confluent/
- http://xcat.org/files/xcat/repos/yum/2.16/xcat-core/
