### ISSUE TITLE
nodeattrib does not restrict setting discovery.policy to policy values

### ISSUE THREAD

**Issue by dbrajendra** [xcat2/confluent#84]
The confluent discovery policy can currently be set to: manual, open or permissive.
(see https://hpc.lenovo.com/users/documentation/confluentdisco.html).

Confluent has no error checking to ensure this value is correct set by the user.
Example:

nodeattrib node001 discovery.policy
node001: discovery.policy: permissive

nodeattrib node001 discovery.policy=apple
node001: apple

nodeattrib r164c05s01 discovery.policy
node001: discovery.policy: apple

We  should improve the code to contain error checking for confluent settings to prevent the user entering incorrect values in those database fields where fixed values are expected.
This specific example is for the discovery.policy setting but a more extensive review should be done for all database fields to improve user experience.

Code level tested on:
lenovo-confluent-0.7.1-1.noarch
confluent_server-1.7.2-1.noarch
confluent_client-1.7.2-1.noarch

**Comment by jjohnson42** [comment]
This is in the forthcoming 2.2 release, among other attributes
