### ISSUE TITLE
Add option to nodediscover command to only report undiscovered devices

### ISSUE THREAD

**Issue by dbrajendra** [xcat2/confluent#85]
It would be useful to add an option on the nodediscover list command to report devices that have not been discovered yet.
This change should take into account that another confluent server may have already discovered the device. (e.g. when using multiple xCAT service nodes as confluent servers on the same network segment).

For large-scale cluster discovery this would be useful.

confluent version:
lenovo-confluent-0.7.1-1.noarch
confluent_server-1.7.2-1.noarch
confluent_client-1.7.2-1.noarch

**Comment by jjohnson42** [comment]
https://github.com/xcat2/confluent/commit/91d0c8ed7a321d60435813405d4519e9fc153fda

Also, nodediscover has added the 'clear' which can help more confidently prepare for a clean rescan.

**Comment by jjohnson42** [comment]
per above, implemented
