### ISSUE TITLE
Not all rpm requsites are included in confluent rpm package build

### ISSUE THREAD

**Issue by dbrajendra** [xcat2/confluent#86]
If a user wants to install or upgrade confluent independently of xCAT then the confluent rpm packages do not include all the rpm requisite packages are needed.

For example in confluent 1.7.1 the requisite rpm is required otherwise things do not work:
python-pyghmi

Other rpms that may be required from the Lenovo confluent/xCAT bundle:
python-eventlet
python-greenlet
python2-pyte

Confluent version tested on:
lenovo-confluent-0.7.1-1.noarch
confluent_server-1.7.2-1.noarch
confluent_client-1.7.2-1.noarch

**Comment by whowutwut** [comment]
@jjohnson42 could you take a look at this one?

**Comment by jjohnson42** [comment]
The next rpms will have more specific version requirements.  Strictly speaking the other packages aren't *required* to be updated, though updates are available...

**Comment by jjohnson42** [comment]
https://github.com/xcat2/confluent/commit/2628683881da5733ae0dd0127b7970b796afb3c6

I only boosted the pyghmi, as the other versions are optional updates, as far as is known.

Also, the suggested way to update from a single repo:
https://hpc.lenovo.com/users//documentation/updatesw_rhel.html
