### ISSUE TITLE
Would like an option to power off nodes as they are discovered

### ISSUE THREAD

**Issue by dbrajendra** [xcat2/confluent#93]
At present when you discover nodes they remain powered on.
It would be useful to have an node attribute to indicate what to do next (e.g. power off the node or do some other tasks).

**Comment by jjohnson42** [comment]
For xCAT or confluent?

In confluent, you don't even necessarily turn it on.  I generally do it turned off.

Now in-band discovery would be this way.

Of course an 'on-discover' handler that could do open ended things would make sense, particularly for things like 'I detected a pxe-client and matched mac, export it to <software of choosing>"

**Comment by jjohnson42** [comment]
Closing as confluent discovery can be done while off, and for now assuming we don't need to auto feed to other software on discover...
