### ISSUE TITLE
When an SMM is discovered would be useful to populate id.model and id.serial attributes

### ISSUE THREAD

**Issue by dbrajendra** [xcat2/confluent#96]
When we discover an SMM we do not populate the id.model and id.serial attributes in the confluent database. Example:

[root@cresco6mg1 ~]# nodeattrib smm01
smm01: console.logging: full
smm01: console.method: ipmi
smm01: discovery.policy: permissive,pxe
smm01: groups: smm,rack01-smm,everything
smm01: hardwaremanagement.manager: smm01
smm01: pubkeys.tls_hardwaremanager: string
smm01: secret.hardwaremanagementpassword: ********
smm01: secret.hardwaremanagementuser: ********

However when we discovery a node this information is populated:
[root@cresco6mg1 ~]# nodeattrib nodex001
nodex001: console.logging: full
nodex001: console.method: ipmi
nodex001: discovery.policy: permissive,pxe
nodex001: enclosure.bay: 1
nodex001: enclosure.manager: smm01
nodex001: groups: ipmi,compute,rack01,everything
nodex001: hardwaremanagement.manager: nodex001-xcc
nodex001: id.model: 7X21CTO1WW
nodex001: id.serial: ABC1234
nodex001: id.uuid: string
nodex001: net.switch: switch01
nodex001: net.switchport: 1
node001: pubkeys.tls_hardwaremanager: string
nodex001: secret.hardwaremanagementpassword: ********
nodex001: secret.hardwaremanagementuser: ********

It would be nice to have this feature added.
Work-around is to get the information using the nodeattrib command.

**Comment by jjohnson42** [comment]
In an upcoming firmware update, will be able to do this in a way consistent with how we do it for those systems, tempted to delay until that can be done consistently..

**Comment by jjohnson42** [comment]
This occurs with current SMM firmware
