### ISSUE TITLE
nodefirmware update fails with ioerror

### ISSUE THREAD

**Issue by dbrajendra** [xcat2/confluent#97]
During updates of system firmware of 36 nodes in parallel we found one step failed with ioerror being reported for most nodes and stuck in initialising for a few.
you needed to ctrl-c the operation as it was not working.

It seemed that confluent had just rotated the sdterr log file and we saw an error trace like this:

/var/log/confluent/stderr:
May 15 10:44:13 {"previouslogfile": "/var/log/confluent/stderr.2018-05-13"}
May 15 10:44:13   File "/usr/lib64/python2.7/threading.py", line 814, in __bootstrap_inner
    (self.name, _format_exc())): Exception in thread Thread-288:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/pyghmi/ipmi/oem/lenovo/imm.py", line 57, in run
    self.rsp = self.wc.upload(self.url, self.filename, self.data)
  File "/usr/lib/python2.7/site-packages/pyghmi/util/webclient.py", line 143, in upload
    data = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: u'/software/fw-thinksystem-sr630-sr650-lxpm/lnvgy_fw_lnvgy_fw_drvln_pdl212s-1.20_anyos_noarch.uxz'
May 15 10:44:13   File "/usr/lib64/python2.7/threading.py", line 814, in __bootstrap_inner
    (self.name, _format_exc())): Exception in thread Thread-289:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/pyghmi/ipmi/oem/lenovo/imm.py", line 57, in run
    self.rsp = self.wc.upload(self.url, self.filename, self.data)
  File "/usr/lib/python2.7/site-packages/pyghmi/util/webclient.py", line 143, in upload
    data = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: u'/software/fw-thinksystem-sr630-sr650-lxpm/lnvgy_fw_lnvgy_fw_drvln_pdl212s-1.20_anyos_noarch.uxz'

The nodefirmware command would consistently fail in the same manner if you repeated the attempt to update the firmware.
A restart of the confluent service (systemctl restart confluent) clear the issue.

Confluent version:
lenovo-confluent-0.8.1-1.noarch
confluent_client-1.8.2-1.noarch
confluent_server-1.8.2-1.noarch

**Comment by jjohnson42** [comment]
Messages have been improved on this front
