### ISSUE TITLE
nodefirmware update should not leave status in pending state once firmware update is complete

### ISSUE THREAD

**Issue by dbrajendra** [xcat2/confluent#98]
If you run "nodefirmware node-range update firmware-image" you will see a status like this when
the firmware update is complete:

lnode01:pending: 100%      lnode02:pending: 100%      xcat1:pending: 100%   
xcat2:pending: 100%      xcat3:pending: 100%      xcat4:pending: 100%   

The state should not be "pending" when the update is successful.
Even though the update is "100%" the "pending" status is slightly confusing to the user.

Consider changing this status to report "success", "completed" or another appropriate label to make it clear to the use that the update is finished.

Confluent version:
lenovo-confluent-0.8.1-1.noarch
confluent_client-1.8.2-1.noarch
confluent_server-1.8.2-1.noarch

**Comment by jjohnson42** [comment]
So the 'pending' means the update is waiting on some action to become active.  For FPC, it goes to complete as no further action is required.

Currently the nodefirmware man page says:
  The  firmware  update  process  has  completed,  but  the
           firmware will not be  active  until  the  relevant  component  next
           resets.  Generally speaking, for UEFI update the system will need a
           reboot, and for BMC updates, the nodebmcreset  command  will  begin
           the process to activate the firmware.

**Comment by jjohnson42** [comment]
Closed as pending is intended to indicate the user that some potentially disrutive reboot is needed to fully complete the activation of a firmware.
