### ISSUE TITLE
Node groups are not cleaned up when  noderemove used to delete a node

### ISSUE THREAD

**Issue by dbrajendra** [xcat2/confluent#99]
I you add nodes to confluent:

makeconfluentcfg ipmi (where ipmi is an xCAT nodegroup containing nodea, nodeb and nodec)
This command automatically defines the nodegroups and nodes to confluent.

if you delete the node later:

noderemove nodec

The node is still in the "ipmi" confluent group.
This results in unexpected errors.
Example: 

# nodehealth ipmi  | collate -a
Unexpected error

The /var/log/confluent/trace file commands about KeyError on the missing node.
Jun 01 13:54:24 Traceback (most recent call last):
  File "/opt/confluent/lib/python/confluent/sockapi.py", line 120, in sessionhdl
    connection, request, cfm, authdata, authname, skipauth)
  File "/opt/confluent/lib/python/confluent/sockapi.py", line 178, in process_re
quest
    hdlr = pluginapi.handle_path(path, operation, cfm, params)
  File "/opt/confluent/lib/python/confluent/core.py", line 722, in handle_path
    pathcomponents, autostrip)
  File "/opt/confluent/lib/python/confluent/core.py", line 665, in handle_node_r
equest
    if attrname in nodeattr[node]:
KeyError: 'nodec'

The problem is possibly two issues. Some points to consider:
1.  If we delete a node from confluent should the node also be removed form and nodegroups?
2. If a non-existent node is defined in a node group why does this generate trace file errors?
3. Should we have a method to add/remove individual attributes form confluent node groups ?
   At present I think you have to define the nodegroup again (minus the objects you want to remove from the group

Confluent version:
confluent_client-1.8.2-1.noarch
lenovo-confluent-0.8.1-1.noarch
confluent_server-1.8.2-1.noarch

**Comment by jjohnson42** [comment]
I'm not able to reproduce this one, at least not anymore...

nodegroupattrib can be used to modify nodegroup attributes.

Currently an empty group is possible to have in confluent, but not in xCAT

**Comment by jjohnson42** [comment]
Have been unable to produce for a long time.
